/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RemoteOperations_constants.h"

namespace RemoteOperations { namespace thrift { namespace impl {

const RemoteOperationsConstants g_RemoteOperations_constants;

RemoteOperationsConstants::RemoteOperationsConstants() {
}

}}} // namespace

