/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RemoteOperations_CONSTANTS_H
#define RemoteOperations_CONSTANTS_H

#include "RemoteOperations_types.h"

namespace RemoteOperations { namespace thrift { namespace impl {

class RemoteOperationsConstants {
 public:
  RemoteOperationsConstants();

};

extern const RemoteOperationsConstants g_RemoteOperations_constants;

}}} // namespace

#endif
